---

- hosts: all
  become: true
  tasks:
  - name: update apt cache
    apt:
      update-cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support to apache
    apt:
      name: libapache2-mod-php
      state: latest

