---

- hosts: all
  become: true
  tasks:
  - name: update apt cache
    apt:
      update-cache: yes

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove php support to apache
    apt:
      name: libapache2-mod-php
      state: absent
